### ISSUE TITLE
[BETA] Add to plan flow improvement

### ISSUE THREAD

**Issue by anindilla** [cookpad/community#1]
## **Summary :beer:**
When users press `add to plan`, we will prompt them to share:
- When are they going to cook it
- What are they planning to do when they're cooking it

So that they can be:
- Educated on how to use the button properly
- The first content of their log will be fruitful
- Reminded to cook it if they forgot to do so

## **Problems Being Solved :frowning:**
- Users cannot differentiate the value proposition of `add to plan` button vs `bookmark` as they thought both have the same purpose of saving the recipe
- Lots of users added to plan but never mark the recipe as `cooked`

## **Solution Description :rocket:**
<img width="250" alt="Screenshot 2019-08-16 at 16 07 56" src="https://user-images.githubusercontent.com/8868463/63177576-21dbbe80-c040-11e9-84a4-8ef43ed52a6b.png">
<img width="250" alt="Screenshot 2019-08-16 at 16 08 08" src="https://user-images.githubusercontent.com/8868463/63177577-21dbbe80-c040-11e9-899c-c84172de8355.png">

- After clicking add to plan, users will be prompted to mention when they're going to cook it: Now, Today, Tomorrow, This Week, and Not Sure
- Clicking `now` will prompt them to open the tray, so that they can review the recipe, modify if necessary, and start cooking
- Clicking `today`, `tomorrow` or `this week` will prompt them to open `all logs` page, then we will ask them to make some notes about what they want to try when cooking the dish. If they haven't cooked it until the time is up, they will be reminded via a `call-out` on top of the `cookplan tray`
- Clicking `not sure` will prompt them to keep it in bookmark instead. Users can choose to also keep it in the plan if they want to.

## **Metrics Impacted :ok_hand:**
- Increased adaptation of `add to plan`
- Increased number of interactions in `cooking logs`

## **Beta Scenario ✅**
- When do usually users want to cook it? Do they actually cook it in the specified time?
- Do users end up writing some prompts after adding to plan when we direct them to the log page?
- Does this affect their `add to plan` and `cooked it` usage?
- Do they understand the value of this feature? Do they know where they are? What pages are they facing right now?

## **Related Links 🔎**
Figma link: https://www.figma.com/file/VT2f5WnfRYd7KIK3M7iaVS/Add-to-plan-Flow---Week-1

**Comment by CarlJonesCookpad** [comment]
### **Data Requirements:**

**Logging Needed:**

    **event**
    ` intercept.show`
    **ref**
     `add_to_plan_intercept`
     
    **event**
     `intercept.click`
    **ref**
     `add_to_plan_intercept`
    **keyword**
     which button they press on the .click event (`Now / Today / Tomorrow / Later / Don't Know`)

**Comment by waliahimanshu** [comment]
@anindilla 
For translations pls :


    <string name="when_will_you_cook_title"><![CDATA[When are you going to cook <b>%1$s</b>]]></string>
    <string name="not_sure_chip">Not sure</string>
    <string name="not_sure_cooking_title">Move this recipe to your bookmarks to cook later? </string>
    <string name="not_sure_bookmarked">Bookmarked %1$s</string>
    <string name="keep_in_plan_chip">Keep in plan</string>
    <string name="bookmark_it_chip">Bookmark it</string>
    <string name="now_chip">Now</string>
    <string name="now_cooking_msg"><![CDATA[🎉 Yay! Happy cooking then!]]></string>
    <string name="today_chip">Today</string>
    <string name="tomorrow_chip">Tomorrow</string>
    <string name="this_week_chip">This week</string>
    <string name="thread_prompt_msg">Add a note for later</string>
    <string name="thread_prompt_comment_hint">What are you going to try?</string>

**Comment by anindilla** [comment]
<string name="when_will_you_cook_title"><![CDATA[Kapan kamu berencana untuk memasak <b>%1$s</b>]]></string>
<string name="not_sure_chip">Tidak tahu</string>
<string name="not_sure_cooking_title">Pindahkan resep ke Cookmark?</string>

**can i propose to add one more body below the not sure cooking title?**
<string name="not_sure_cooking_body">Rencana masak sebaiknya digunakan bila kamu sudah tahu kapan kamu hendak memasaknya, terutama dalam waktu dekat.</string>

<string name="not_sure_bookmarked">Resep tersimpan di Cookmark %1$s</string>
<string name="keep_in_plan_chip">Tetap di rencana masak</string>
<string name="bookmark_it_chip">Pindahkan ke Cookmark</string>
<string name="now_chip">Sekarang</string>
<string name="now_cooking_msg"><![CDATA[🎉Oke! Selamat memasak!]]></string>
<string name="today_chip">Hari Ini</string>
<string name="tomorrow_chip">Besok</string>
<string name="this_week_chip">Minggu Ini</string>
<string name="thread_prompt_msg">Tambah catatan memasak</string>
<string name="thread_prompt_comment_hint">Apa yang hendak kamu coba saat memasak nanti?</string>
