### ISSUE TITLE
[BETA] Custom Foreground In-App Notification

### ISSUE THREAD

**Issue by anindilla** [cookpad/community#2]
## **Summary :beer:**
We will send push notifications in the app when users are opening Cookpad through custom view instead of relying on native push behavior

## **Problems Being Solved :frowning:**
- iOS and web does not support native foreground push notification
- We want to convey the "liveliness" feeling more clearly to users via push notification, but sometimes the preview does not show when you're opening the app (or other apps). Need to preserve the preview better.

## **Solution Description :rocket:**
<img width="250" alt="Screenshot 2019-08-16 at 16 07 28" src="https://user-images.githubusercontent.com/8868463/63178157-5a2fcc80-c041-11e9-8dc2-b97c276097a0.png">

- For every push notification we have, when users are opening Cookpad app, we will show the push in the app instead of through native push icon
- Clicking the custom push will do similar action vs clicking push notification
- The event needs to be logged differently in order to differentiate the traffic source

## **Metrics Impacted :ok_hand:**
Increase in community funnel effectiveness, specifically for:
- Log interactions
- Cooked it

## **Beta Scenario :ballot_box_with_check:**
- Ask users to publish a recipe or add to plan, then to let CMs know what the title/link is
- CMs/product team initiated add to plan action, let users stay on the app
- Ensure users see the foreground push

## **Related Links :mag_right:**
Figma link: https://www.figma.com/file/VT2f5WnfRYd7KIK3M7iaVS/Add-to-plan-Flow---Week-1?node-id=0%3A1

**Comment by CarlJonesCookpad** [comment]
**Data Requirements** @waliahimanshu 

**Mixpanel Logging Needed**
Events to show a user has received a push notification
event - `push_notification.show` (new event)
ref - `recipe_page`
keyword - `explanation of what the push notification says`

Events to show a user clicking through from a push notification
Let's catch up on the ones Koya has already briefed into you to split out the in app v out of app ones - https://github.com/cookpad/create-squad/issues/2097

**Comment by waliahimanshu** [comment]
> **Data Requirements** @waliahimanshu
> 
> **Mixpanel Logging Needed**
> Events to show a user has received a push notification
> event - `push_notification.show` (new event)
> ref - `recipe_page`
> keyword - `explanation of what the push notification says`
> 
> Events to show a user clicking through from a push notification
> Let's catch up on the ones Koya has already briefed into you to split out the in app v out of app ones - [cookpad/create-squad#2097](https://github.com/cookpad/create-squad/issues/2097)

@CarlJonesCookpad @koya-matsuno 
We decided to go with native push with a high priority instead custom foreground notif only.
So the os will display a pop-up notification, irrespective when app is background, foreground or not running. 
We will do it for `chat` and `cooking log comments and replies` notifications only.

I believe we can track these push as  `High priority` and they should have high % of user clicking through.

**Comment by CarlJonesCookpad** [comment]
Catch up first thing tomorrow if that works for you? Or i can do later today? @waliahimanshu

**Comment by anindilla** [comment]
Parked.
