### ISSUE TITLE
[BETA] Cooked it & reminder flow improvement

### ISSUE THREAD

**Issue by anindilla** [cookpad/community#3]
## **Summary :beer:**
When the timing of `add to plan` reached its limit (refer to [https://github.com/cookpad/community/issues/1](url)), we will show a callout that will prompt them to share whether or not they have cooked it.

When users press `cooked it` (from any flow), we will prompt them to share:
- Do they like how it tasted or not
- What kind of learnings/discoveries they made in the process

So that they can be:
- Educated on how to use the button and tray properly (to always cook/remove when necessary)
- Encouraged to share photo + text log entry

## **Problems Being Solved :frowning:**
- The flow from `cooked it` to `logs` pages are broken, users are not sure how to use it and how to create content on it
- Lots of users' top of mind feedback mechanism is through Cooksnaps, but we do not clearly communicate that photo + text entry is the replacement of Cooksnaps

## **Solution Description :rocket:**
<img width="360" alt="Screenshot 2019-08-16 at 17 11 22" src="https://user-images.githubusercontent.com/8868463/63181811-ea254480-c048-11e9-8524-e0527bc81532.png">

- Users will be notified from call-out to the tray when they haven't cooked the recipe within the specified time
- Immediate call-out: How does it taste?
- Feedback call-out: Like it or not, we'll prompt them to share their learnings/discovery, or what they'd do differently to improve the taste
- Logs call-out: We'll prompt users to share photos as well

## **Metrics Impacted :ok_hand:**
- Increased number of `cooked it` per user
- Increased number of photo + text entry on log

## **Beta Scenario :ballot_box_with_check:**
**Through reminder**
- Ask users to set a timing for `add to plan` as they wish (today/tomorrow ideally)
- When they check the app the next time during the period, see if they receive the call-out
- Ask them to share some tips, follow the flows until adding log entry

**Through tray**
- Ask users to `cook` a recipe normally from the tray
- Let them follow similar flow

## **Related Links :mag_right:**
Figma link: https://www.figma.com/file/6HDKkDRsq7aQLBGMepCl50/Cooked-it-Experience-Callouts---Week-1?node-id=0%3A1

## **Data Mixpanel Logging Requirements**

**Intercept 1**
event - `intercept.show`
ref - `dyc_did_you_cook_intercept`
event - `intercept.click`
ref - `dyc_did_you_cook_intercept`
keyword - which button they press on the click event (`Cooked it` / `Not Yet`)

**Intercept 2**
event - `intercept.show`
ref - `dyc_how_did_it_work_out_intercept`
event - `intercept.click`
ref - `dyc_how_did_it_work_out_intercept`
keyword - which button they press on the click event (`Up` / `Down` / `Dismiss`)

**Intercept 3**
event - `intercept.show`
ref - `dyc_add_a_comment_up_intercept`
event - `intercept.click`
ref - `dyc_add_a_comment_up_intercept`
keyword - which button they press on the click event (`Yay I'm in`)

**Intercept 4**
event - `intercept.show`
ref - `dyc_add_a_comment_down_intercept`
event - `intercept.click`
ref - `dyc_add_a_comment_down_intercept`
keyword - which button they press on the click event (`Share`)

**Comment by waliahimanshu** [comment]
```
 <string name="dyc_title">Did you cook this recipe ?</string>
    <string name="dyc_not_yet">NOT YET</string>
    <string name="dyc_yay_i_am_in">Yay I\'am in</string>
    <string name="dyc_dislike_title">Oh No! 😢</string>
    <string name="dyc_dislike_msg">Would you like to share a comment or a photo to help others cook it!</string>
    <string name="dyc_how_did_it_taste">What did it taste like? </string>
    <string name="dyc_not_cooked_title">OK !</string>
    <string name="dyc_not_cooked_msg">This recipe will stay in your plan until you cook it!</string>
    <string name="dyc_not_cooked_msg_cta">GOT IT</string>
    <string name="dyc_like_title">Nice! 😋</string>
    <string name="dyc_like_disc">Add a comment or a photo to help others cook it!</string>
```

**Comment by anindilla** [comment]
<string name="dyc_title">Apa kamu sudah memasak resep ini?</string>
    <string name="dyc_not_yet">BELUM</string>
    <string name="dyc_yay_i_am_in">Oke!</string>
    <string name="dyc_dislike_title">Oh Tidak! 😢</string>
    <string name="dyc_dislike_msg">Maukah kamu membagikan komentar atau foto untuk membantu pengguna lain memasak resep ini lebih baik lagi?</string>
    <string name="dyc_how_did_it_taste">Apakah berhasil? </string>
    <string name="dyc_not_cooked_title">OKE!</string>
    <string name="dyc_not_cooked_msg">Resep ini akan tetap ada di Cookplan sampai kamu memasaknya!</string>
    <string name="dyc_not_cooked_msg_cta">OKE!</string>
    <string name="dyc_like_title">Mantap! 😋</string>
    <string name="dyc_like_disc">Bagikan komentar atau foto untuk membantu pengguna lain!</string>
